# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vector_search.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vector_search.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()



DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vector_search.proto\x12\x0cvectorsearch")\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\t\n\x01k\x18\x02 \x01(\r"*\n\x0cSearchResult\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02"=\n\x0eSearchResponse\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.vectorsearch.SearchResult2Z\n\x13VectorSearchService\x12\x43\n\x06Search\x12\x1b.vectorsearch.SearchRequest\x1a\x1c.vectorsearch.SearchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_search_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SEARCHREQUEST']._serialized_start=37
  _globals['_SEARCHREQUEST']._serialized_end=78
  _globals['_SEARCHRESULT']._serialized_start=80
  _globals['_SEARCHRESULT']._serialized_end=122
  _globals['_SEARCHRESPONSE']._serialized_start=124
  _globals['_SEARCHRESPONSE']._serialized_end=185
  _globals['_VECTORSEARCHSERVICE']._serialized_start=187
  _globals['_VECTORSEARCHSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
